# Change these first
owner: Thibault-R # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Nord Compo
    url: https://nordcompo.fr/
    icon: https://nordcompo.fr/app/uploads/2020/01/logonc-1.png
    expectedStatusCodes:
      - 404
  - name: NordSoft
    url: https://www.nordsoft.fr/
    method: GET
    icon: https://www.nordsoft.fr/wp-content/uploads/2020/02/nordsoft-logo-1.png
  - name: Libeo
    url: https://www.libeo.net/
    method: POST
  - name: Google
    check: "tcp-ping"
    url: 46.28.246.123
    port: 80
  - name: Comité France Chine
    url: http://cfc.libeo.net/
  - name: ClicEdit - Dév
    url: http://clicedit.libeo.net/
  - name: ClicEdit - Prod
    url: http://www.clicedit.com/
    
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Statut - Sites Libeo
  introTitle: "**Libeo**"
  introMessage: Page de test uptime/downtime.
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
notification:
  - type: telegram
  
i18n:
  status: Statut
  history: Historique
  responseTime: Délai de réponse
  uptime: Temps
  up: 🟩 En ligne
  degraded: 🟨 Problèmes
  down: 🟥 Hors ligne
  responseTimeGraphAlt: Graphique délai de réponse
  ms: ms
  liveStatus: Sites Live
  allSystemsOperational: 🟩 Tout les sites sont en ligne
  degradedPerformance: 🟨 Problèmes détectées sur les sites
  completeOutage: 🟥 Panne complète
  partialOutage: 🟧 Panne partielle

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
