# Change these first
owner: Thibault-R # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Nord Compo
    url: https://nordcompo.fr/
    icon: https://nordcompo.fr/app/uploads/2020/01/logonc-1.png
  - name: NordSoft
    url: https://www.nordsoft.fr/
    icon: https://www.nordsoft.fr/wp-content/uploads/2020/02/nordsoft-logo-1.png
  - name: Libeo
    url: https://www.libeo.net/
    verify_peer: true
  - name: Comité France Chine
    url: http://cfc.libeo.net/
    verify_peer: true
  - name: ClicEdit - Dév
    url: http://clicedit.libeo.net/
    verify_peer: true
  - name: ClicEdit - Prod
    url: http://www.clicedit.com/


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Statut - Sites Libeo
  introTitle: "**Libeo**"
  introMessage: Page de test uptime/downtime.
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
